name: Build and Push Demo Playback Docker Image

on:
  push:
    branches: [ "main" ]  # or your default branch
    paths:
      - 'containers/demo-playback/**'  # Only trigger on changes in this folder

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: containers/demo-playback  # Specify the folder containing Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: tfoldi/go2-demo-playback:latest
